import "server-only";

/**
 * Server-only commander name exclusions.
 *
 * Every entry is already lowercase and diacritic-folded because the policy
 * compares against moderation variants, not the display value.
 *
 * Match semantics are intentionally split:
 * - role words: whole-token impersonation checks;
 * - reserved keys: exact compact identity checks;
 * - brand keys: compact substring checks for platform/game impersonation;
 * - blocked words: whole-token and exact compact harmful-content checks;
 * - compact terms: only high-confidence fragments safe for substring matching.
 */

export const RESERVED_COMMANDER_DISPLAY_ROLE_WORDS = new Set([
  "admin",
  "administrator",
  "administrador",
  "administracao",
  "moderador",
  "moderator",
  "moderation",
  "moderacao",
  "staff",
  "support",
  "suporte",
  "system",
  "sistema",
  "official",
  "oficial",
  "security",
  "seguranca",
  "root",
  "superuser",
]);

export const RESERVED_COMMANDER_HANDLE_ROLE_WORDS = new Set([
  ...RESERVED_COMMANDER_DISPLAY_ROLE_WORDS,
  "adm",
  "mod",
  "developer",
  "desenvolvedor",
  "dev",
  "owner",
  "dono",
  "proprietario",
  "founder",
  "fundador",
  "operator",
  "operador",
  "helpdesk",
  "atendimento",
  "webmaster",
  "service",
  "servico",
  "bot",
  "team",
  "equipe",
  "verified",
  "verificado",
  "verification",
  "verificacao",
  "account",
  "conta",
  "billing",
  "payments",
  "pagamentos",
  "finance",
  "financeiro",
]);

export const RESERVED_COMMANDER_BRAND_KEYS = new Set([
  "bellumcivile",
  "warbrasil",
]);

export const RESERVED_COMMANDER_NAME_KEYS = new Set([
  ...RESERVED_COMMANDER_HANDLE_ROLE_WORDS,
  "bellum",
  "bellumcivile",
  "bellumofficial",
  "bellumoficial",
  "bellumstaff",
  "bellumsupport",
  "bellumsuporte",
  "bellumadmin",
  "bellummoderation",
  "bellumcivilegame",
  "bellumcivileofficial",
  "bellumcivileoficial",
  "warbrasil",
  "warbrasilofficial",
  "warbrasiloficial",
  "warbrasilstaff",
  "warbrasilsupport",
  "warbrasilsuporte",
  "warbrasiladmin",
  "administratorbellum",
  "administradorbellum",
  "officialbellum",
  "oficialbellum",
]);

export const BLOCKED_COMMANDER_WORDS = new Set([
  // Portuguese — profanity, explicit sexual language and common abusive terms.
  "caralho",
  "caralhos",
  "porra",
  "porras",
  "merda",
  "merdas",
  "puta",
  "putas",
  "puto",
  "putos",
  "putaria",
  "foder",
  "fode",
  "foda",
  "fodase",
  "fodido",
  "fodida",
  "buceta",
  "boceta",
  "cuzao",
  "cuzona",
  "arrombado",
  "arrombada",
  "piranha",
  "vadia",
  "vagabunda",
  "vagabundo",
  "cacete",
  "piroca",
  "rola",
  "punheta",
  "boquete",
  "viado",
  "traveco",

  // English — profanity, explicit sexual language and common slurs.
  "fuck",
  "fucks",
  "fucker",
  "fuckers",
  "fucking",
  "fucked",
  "shit",
  "shits",
  "shitty",
  "bitch",
  "bitches",
  "cunt",
  "cunts",
  "asshole",
  "assholes",
  "motherfucker",
  "motherfuckers",
  "pussy",
  "pussies",
  "dick",
  "dicks",
  "cock",
  "cocks",
  "whore",
  "whores",
  "slut",
  "sluts",
  "wanker",
  "wankers",
  "bastard",
  "bastards",
  "nigger",
  "nigga",
  "faggot",
  "retard",
  "retarded",
  "tranny",
  "kike",
  "spic",

  // Spanish — strong profanity and abusive terms.
  "mierda",
  "mierdas",
  "joder",
  "jodete",
  "cabron",
  "cabrones",
  "pendejo",
  "pendeja",
  "pendejos",
  "pendejas",
  "chingar",
  "chingada",
  "chingado",
  "culero",
  "culera",
  "maricon",
  "maricones",

  // High-confidence hate/extremist references.
  "nazi",
  "nazis",
  "nazista",
  "nazistas",
  "neonazi",
  "neonazis",
  "hitler",
  "heilhitler",
  "whitepower",
  "whitesupremacy",
  "kukluxklan",
  "kkk",

  // Explicit sexual / exploitation references.
  "porn",
  "porno",
  "pornografia",
  "pornography",
  "pornographic",
  "pornhub",
  "hentai",
  "rule34",
  "xxx",
  "pedofilo",
  "pedofila",
  "pedofilia",
  "pedophile",
  "pedophilia",
  "lolicon",
  "shotacon",
  "childporn",
  "childpornography",
  "csam",
]);

export const BLOCKED_COMMANDER_COMPACT_TERMS = new Set([
  // Only fragments with sufficiently low false-positive risk belong here.
  "pornografia",
  "pornography",
  "childporn",
  "childpornography",
  "pedofilia",
  "pedophilia",
  "heilhitler",
  "whitepower",
  "whitesupremacy",
  "kukluxklan",
]);
